apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry-pv
  namespace: registry
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOncePod
  hostPath:
    path: "/var/lib/registry"