apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: registry
  labels:
    app: registry 
spec:
  selector:
    app: registry
  ports:
    - name: reg
      protocol: TCP
      port: 5001
      targetPort: 5000


