apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: proxy-service-monitor-prometheus
  namespace: test-env
spec:
  endpoints:
    - honorLabels: true
      port: metrics
      path: metrics
  selector:
    matchLabels:
      app: proxy
