apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: proxy-service-monitor-prometheus
spec:
  endpoints:
    - honorLabels: true
      port: metric
      path: metrics
  selector:
    matchLabels:
      app: proxy
