---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ssh-test
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Dominik-Pfefferle/test-local-crossplane.git
    targetRevision: HEAD
    path: ssh-jumphost
  destination:
    server: https://kubernetes.default.svc
    namespace: example-jh
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
