apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-in-env
  namespace: argocd
  labels:
    name: test-in-env
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/hook-delete-policy: HookFailed
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Dominik-Pfefferle/test-local-crossplane.git
    targetRevision: HEAD
    path: test-in-env
    directory:
      recurse: true

  destination:
    server: https://kubernetes.default.svc
    namespace: test-env
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
    - CreateNamespace=true
  revisionHistoryLimit: 10