apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-iac-ui
  namespace: argocd
  labels:
    name: app-iac-ui
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/hook-delete-policy: HookFailed
  #finalizers:
  #  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Dominik-Pfefferle/test-local-crossplane.git
    targetRevision: HEAD
    path: iac-ui
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 10
